### ISSUE TITLE
Will this project support `polyfill-library@4` and beyond?

### ISSUE THREAD

**Issue by mhassan1** [cdnjs/polyfill-service#4]
## What

The original `polyfill-service` repository has many requests for missing polyfills; for example, https://github.com/polyfillpolyfill/polyfill-service/issues/2756, https://github.com/polyfillpolyfill/polyfill-service/issues/2744, and https://github.com/polyfillpolyfill/polyfill-service/issues/2734. All of the requested polyfills are available in `polyfill-library@4`.

Because this repository vendors the polyfills inside the `polyfill-libraries` directory, it is unclear where they came from and whether they will get updated.

Will this repository ever get additional polyfills from `polyfill-library@4` and beyond? If so, which repository will those polyfills come from? See related conversation at https://github.com/JakeChampion/polyfill-library/issues/1323.

**Comment by xtuc** [comment]
Note that the version 4.8.0  has been added to https://cdnjs.cloudflare.com/polyfill.

**Comment by mhassan1** [comment]
@xtuc I'm assuming 4.8.0 came from https://www.npmjs.com/package/polyfill-library. Is that correct?

If that's correct, given that https://github.com/JakeChampion/polyfill-library/issues/1323 has not gotten a response from the maintainer, you may want to consider getting future `polyfill-library` updates from https://www.npmjs.com/package/@mrhenry/polyfill-library, which is a maintained fork. FYI @romainmenke.

**Comment by xtuc** [comment]
> @xtuc I'm assuming 4.8.0 came from https://www.npmjs.com/package/polyfill-library. Is that correct?

Yes, correct.

**Comment by romainmenke** [comment]
Thank you @xtuc 🙇 

------

> Odd that it's at `v3/` instead of `v4/`, but that's of little concern.

If I recall correctly:
- the hosted service has versioning for it's API (which query params are available, how do they work, ...) 
- the library has versioning for it's API (how does the library work, which polyfills are available, ...)

In v4 of the library we (massive effort by @mhassan1) dropped support for IE8.
But we didn't make changes to other parts of the public interface so this should be fine :)

Given the age of IE8 I don't even think this is breaking for those users who don't set a version string in their url.

-------

> you may want to consider getting future polyfill-library updates from https://www.npmjs.com/package/@mrhenry/polyfill-library, which is a maintained fork

We also took some extra measures:
- no dependencies on packages still under control of the previous maintainer
- all polyfills are vendored (and thus tracked by git)

https://github.com/mrhenry/polyfill-library/blob/main/CHANGELOG.md#v500

**Comment by xtuc** [comment]
https://cdnjs.cloudflare.com/polyfill supports 4.8.0.
