### ISSUE TITLE
polyfill.io replacement is slower

### ISSUE THREAD

**Issue by gkiely** [cdnjs/polyfill-service#5]
I'd like to move to cloudflare instead of polyfill.io but the performance seems to be slower. 

Details: https://blog.cloudflare.com/polyfill-io-now-available-on-cdnjs-reduce-your-supply-chain-risk

```sh
curl -o /dev/null -s -w "time_total: %{time_total} sec\nsize_download: %{size_download} bytes\n" "https://polyfill.io/v3/polyfill.min.js"

time_total: 0.126982 sec
size_download: 87412 bytes
```

```sh
curl -o /dev/null -s -w "time_total: %{time_total} sec\nsize_download: %{size_download} bytes\n" "https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js"

time_total: 0.530253 sec
size_download: 87412 bytes
```

Can also be seen by navigating directly to a URL:

https://polyfill.io/v3/polyfill.min.js?features=default%2CIntersectionObserver%2CElement.prototype.closest
<img width="1264" alt="image" src="https://github.com/cdnjs/cdnjs/assets/1948935/f6c0db82-a09d-4533-95d7-c8af608e398b">

https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=default%2CIntersectionObserver%2CElement.prototype.closest
<img width="1281" alt="image" src="https://github.com/cdnjs/cdnjs/assets/1948935/2acce219-a10e-4c46-a034-bb584bf62dd5">

Perf test:
https://tools.keycdn.com/performance?url=https://polyfill.io/v3/polyfill.min.js
https://tools.keycdn.com/performance?url=https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js

**Comment by JZebra** [comment]
I have the same concern. We are considering moving from our self-hosted polyfill.io instance to the cloudflare one, but it is slower. 

https://tools.keycdn.com/performance?url=https://www.everlane.com/polyfill/v3/polyfill.min.js

I think the difference is edge caching. Requests to https://polyfill.io/v3/polyfill.min.js and https://www.everlane.com/polyfill/v3/polyfill.min.js have a `Cf-Cache-Status` response header, but https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js does not.

**Comment by MattIPv4** [comment]
👋 Hey folks, it looks like there was a configuration issue when this was initially deployed, and caching hadn't been enabled in front of the Worker that was serving these requests. Caching has now been added, and the respond times are looking much better:

<img width="773" alt="image" src="https://github.com/cdnjs/polyfill-service/assets/12371363/411d77df-62a0-4c23-85c0-3c601f2cddad">

**Comment by gkiely** [comment]
Much appreciated @MattIPv4 👍
